### ISSUE TITLE
"Double Check ACE hits" commands need include statement adjusted

### ISSUE THREAD

**Issue by ngrovhoug** [PackeTsar/ASA-Cleanup#2]
The "| in line X" need to have an underscore after the ACE line. 

Without this the show command will return an access-list lines that start with the entry number.
For example:
'show access-list OUTSIDE_access_in | in line 1'
this returns any list entry beginning with 1, like 10, 14, or 115 (god forbid)

To resolve this add an underscore  after the ACE. '_' tells the CLI to search for entries with a space after the number. 

Fixed with "show access-list {{acl}} | in line {{ace}}_" on line 334 and 338

Thanks for this.

**Comment by PackeTsar** [comment]
So there is a trailing space which is added. Changing that to an underscore in case it gets removed by editors.

**Comment by PackeTsar** [comment]
Fixed. Closing
