### ISSUE TITLE
VirusTotal check - 6 engines detected this file

### ISSUE THREAD

**Issue by jdelaram** [PackeTsar/ASA-Cleanup#3]
Just checked your windows binary file(ASA-Cleanup.exe) on https://www.virustotal.com/ and got these results : 

CrowdStrike Falcon: :
malicious_confidence_60% (W)
eGambit
Trojan.Generic

McAfee-GW-Edition:
BehavesLike.Win32.Generic.vc
Sophos ML
heuristic

TheHacker:
Trojan/Generik.IJNZZHZ
Yandex
Trojan.DownLoader!

Can you explain why?

**Comment by PackeTsar** [comment]
No idea. It was compiled with process outlined in the [Compile](https://github.com/PackeTsar/ASA-Cleanup#compile) section of the README. Compile it yourself if there is any question about the binary. I think I will probably recompile the latest and check that against virustotal just to be safe.

**Comment by jdelaram** [comment]
Will do, thanks.
