### ISSUE TITLE
new analisys implementation

### ISSUE THREAD

**Issue by fabryx87** [PackeTsar/ASA-Cleanup#7]
Hi,
Here there are some analisys that I used:
                run ASA-Cleanup.py -c "^ip local pool" -p 3 CONFIG.txt #for dhcp pool
                run ASA-Cleanup.py -c "^group-policy" -p 1 CONFIG.txt #for group policy
                run ASA-Cleanup.py -c "^tunnel-group" -p 1 CONFIG.txt #for tunnel group
                run ASA-Cleanup.py -c "crypto map .* set peer" -p 6 CONFIG.txt  #for cryptomap
                run ASA-Cleanup.py -c "crypto ipsec .*" -p 4 CONFIG.txt #for ike1 proposal and ike2 trasform set
Thanks for your hard work.
Fabrizio

**Comment by PackeTsar** [comment]
Very nice!
